services:
  pps:
    build:
      context: ./pps
    container_name: pps-service
    ports:
      - "8080:8080"
    depends_on:
      - broker
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - fraud-net

  broker:
    build:
      context: ./broker
    container_name: broker-service
    ports:
      - "8081:8081"
    depends_on:
      - activemq
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - fraud-net

  fcs:
    build:
      context: ./fcs
    container_name: fcs-service
    ports:
      - "8082:8082"
    depends_on:
      - activemq
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    networks:
      - fraud-net
    
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - fraud-net
    
networks:
  fraud-net:
    driver: bridge
