server:
  port: 8083

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  main:
    allow-bean-definition-overriding: true

camel:
  springboot:
    name: fcs-camel-context
    main-run-controller: true

