server:
  port: 8082

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  jms:
	pub-sub-domain: false

camel:
  springboot:
    name: fcs-camel-context
    main-run-controller: true
	
